# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3620ca5f52538926daa6659e9083f95549a50d782f3a0410270af85ff55a74127fb5060ca7b05e97127f390e2fbd537d48c2c51f662a30ef5187f2d81f975ebe

test:
  secret_key_base: ddfceecb633788fb0e7cbabe1fd1e553aaba1e77e3952b1e9198ef9837a0fe69f771a16c7b5dc48fd3966aa5fa2aefe0140619bf7e7a4cd6e294d3a55dc47818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
